# Generated by Django 5.0.6 on 2024-06-10 15:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scooter', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='scooter',
            name='name',
            field=models.CharField(max_length=31, unique=True),
        ),
    ]
